name: Update Semua Data Togel

on:
  schedule:
    - cron: '10 07 * * *'  # SDY: Jam 14:10 WIB (07:10 UTC)
    - cron: '55 10 * * *'  # SGP: Jam 17:55 WIB (10:55 UTC)
    - cron: '05 16 * * *'  # HK:  Jam 23:05 WIB (16:05 UTC)
  workflow_dispatch:

jobs:
  run-all-scrapers:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - run: pip install selenium webdriver-manager
      
      - name: Jalankan SDY
        run: python scraper_sdy.py || echo "SDY belum jamnya"
        
      - name: Jalankan SGP
        run: python scraper_sgp.py || echo "SGP belum jamnya"
        
      - name: Jalankan HK
        run: python scraper.py || echo "HK belum jamnya"

      - name: Push Perubahan
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Update Data Togel Otomatis" || exit 0
          git push
